# Example configuration for test_dependency_plugin plugin
test_dependency_plugin:
  # Enable/disable the plugin
  enabled: true
  
  # Plugin-specific settings
  setting1: "value1"
  setting2: 42
  setting3: true
  
  # Nested configuration
  advanced:
    option1: "advanced_value"
    option2: ["item1", "item2", "item3"]
